[package]
name = "dialoguer"
description = "A command line prompting library."
version = "0.5.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["cli", "menu", "prompt"]
license = "MIT"
homepage = "https://github.com/mitsuhiko/dialoguer"
documentation = "https://docs.rs/dialoguer"
readme = "README.md"

[dependencies]
console = { path="../console", version="0.9.1" }
lazy_static = "1.4.0"
tempfile = "3.1.0"
regex = "1.3.1"
